spring:
  config:
    activate:
      on-profile: local

  management:
    endpoints:
      web:
        exposure:
          include: health,prometheus,metrics
    metrics:
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: true

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://${CATALOG_HOST}:${CATALOG_PORT}
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1

        - id: inventory-service
          uri: http://${INVENTORY_HOST}:${INVENTORY_PORT}
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://${ORDER_HOST}:${ORDER_PORT}
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: http://${PAYMENT_HOST}:${PAYMENT_PORT}
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

      default-filters:
        - PreserveHostHeader
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders:
              - "*"
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
