spring:
  config:
    activate:
      on-profile: dev

  management:
    endpoints:
      web:
        exposure:
          include: health,prometheus,metrics
    metrics:
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: true

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: ${CATALOG_HOST}:${CATALOG_PORT}
          predicates:
            - Path=/catalog/**

        - id: inventory-service
          uri: ${INVENTORY_HOST}:${INVENTORY_PORT}
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: ${ORDER_HOST}:${ORDER_PORT}
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: ${PAYMENT_HOST}:${PAYMENT_PORT}
          predicates:
            - Path=/payment/**

      default-filters:
        - PreserveHostHeader
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders:
              - "*"
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
